name: Update electron documentation survey
on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  updateElectronDataPackages:
    name: Update surveys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
      - run: npm ci
      - name: Update survey info
        env:
          SM_TOKEN: ${{ secrets.SM_TOKEN }}
        run: cd .github/actions && node --unhandled-rejections=strict ./create-survey.js
